use rand::{Rng, RngExt, rngs::ThreadRng};
use rand_distr::{Distribution, Normal};

use crate::arm::ArmLike;

#[derive(Debug, Clone)]
struct NormParams {
    mean: f64,
    std_dev: f64,
}

// Arm with normal distribution
#[derive(Clone, Debug)]
pub struct ArmNorm<R: Rng> {
    params: NormParams,
    norm_distr: Normal<f64>,
    rng: R,
    // rng: rand::rngs::ThreadRng,
    // Random values, which were already
    // generated by this arm (by this distribution)
    values: Vec<f64>,
}

impl ArmNorm<ThreadRng> {
    pub fn new(mean: f64, std_dev: f64) -> Self {
        let thread_rng = rand::rng();
        let normal = Normal::new(mean, std_dev).unwrap();

        Self {
            params: NormParams { mean, std_dev },
            norm_distr: normal,
            rng: thread_rng,
            values: vec![],
        }
    }
}

impl Default for ArmNorm<ThreadRng> {
    fn default() -> Self {
        ArmNorm::new(0.0, 1.0)
    }
}

impl<R: Rng> ArmLike<R> for ArmNorm<R> {
    fn pull(&mut self) -> f64 {
        let rand_val = self.norm_distr.sample(&mut self.rng);
        self.values.push(rand_val);
        rand_val
    }

    fn pull_miltiple(&mut self, len: usize) -> Vec<f64> {
        let rand_vals: Vec<f64> = (&mut self.rng)
            .sample_iter::<f64, _>(self.norm_distr)
            .take(len)
            .collect();

        self.values.extend(&rand_vals);
        rand_vals
    }

    fn with_rng(mean: f64, std_dev: f64, rng: R) -> Self {
        // let thread_rng = rand::rng();
        let normal = Normal::new(mean, std_dev).unwrap();

        Self {
            params: NormParams { mean, std_dev },
            norm_distr: normal,
            rng: rng,
            values: vec![],
        }
    }
}
